# Generated by Django 5.2.1 on 2025-06-04 08:52

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=1024)),
            ],
            options={
                "default_related_name": "campaigns",
            },
            bases=(models.Model, core.models.AppModelMixin),
        ),
    ]
