# Generated by Django 5.2.1 on 2025-06-08 14:33

import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0001_add_campaign_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=1024)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="models.campaign")),
            ],
            options={
                "default_related_name": "strategies",
            },
            bases=(models.Model, core.models.AppModelMixin),
        ),
    ]
